config/routes.rb
MusicProject::Application.routes.draw do
  devise_for :users
  resources :artists

  resources :albums

  resources :songs

  get '/hello', to:  'home#hello'
  root to:  'home#hello'

  get '/purchase', to:  'home#amazon'
  get '/created', to: 'home#created'
  post '/tag_entry', to: 'songs#tag_entry'
  get '/song_error', to: 'songs#song_error'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def hello
  	@color_white = params[:color_white]
  end

  def created
  	render 'shared/created'
  end

  def amazon
  	redirect_to('http://www.amazon.com/mp3')
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
	def pick_guitar(color_wht)
		color_wht_b = to_boolean(color_wht)
		if color_wht_b
			@image = 'FlyingVW.jpg' 
		else
			@image = 'FlyingVN.jpg'
		end
	end

	def to_boolean(str)
		str == 'true'
	end

end

app/views/home/hello.html.erb
<html>
<body>
<center><h1>Welcome to the LctrMusic DB Site</h1>

<%= image_tag(pick_guitar(@color_white)) %>
<br>
<%= link_to 'I want a white guitar!', hello_path(color_white: true) %>
&nbsp;
<%= link_to 'I want a natural guitar!', hello_path(color_white: false) %>
<h3> <%= "Currently tracking #{Song.all.count} songs!" %>
</center>
<br>
<br>
<h2><%= link_to('Take me to the Song Library', songs_path) %></h2>
<h2><%= link_to('Take me to the Album Library', albums_path) %></h2>
<h2><%= link_to('Take me to the Artists List', artists_path) %></h2>

<h2>
<%= link_to('Buy more music!', '/purchase') %></h2>
</body>
</html>