config/routes.rb
MusicProject::Application.routes.draw do
  devise_for :users
  resources :artists

  resources :albums

  resources :songs

  get '/hello', to:  'home#hello'
  root to:  'home#hello'

  get '/purchase', to:  'home#amazon'
  get '/created', to: 'home#created'
  post '/tag_entry', to: 'songs#tag_entry'
  get '/song_error', to: 'songs#song_error'

end

app/models/song.rb
class Song < ActiveRecord::Base

	belongs_to :album
	has_many :sessions
	has_many :musicians, through: :sessions
	has_many :instruments, through: :musicians

  validates :song_title, presence:  true
  validates :duration,
	  :numericality => {:greater_than => 0, :only_integer => true}
  validates :path, presence:  true
  validates :filename, presence: true

  def durationmin 
	  min = (self.duration/60).truncate
	  sec = self.duration.modulo(60)
	  rtn = "#{format('%02d',min)}:#{format('%02d',sec)}"
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  #before_action :edit_warning, only: :edit

  layout 'augmented'

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /tag_entry
  def tag_entry
    @tag_file_name = params[:tag_file_name]
    path = File.expand_path("~/#{@tag_file_name}")
    begin
      @tag = ID3.new(path)
      # puts "Artist = #{@tag.artist}"
      # puts "Album = #{@tag.album_title}"
      # puts "Song Title = #{@tag.song_title}"
      # puts "Song Title Class = #{@tag.song_title.class}"
    rescue
      @err_msg = "Bad .mp3 file name.  Unable to open file."
      render action: :song_error and return
    end
    @song=Song.new
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create

    artist_id = artist_exist_or_new(params[:artist_name])

    album_id = album_exist_or_new(params[:album_name], params[:genre], artist_id)

    @song = Song.new(song_params)
    @song.album_id = album_id

    respond_to do |format|
      if @song.save
        format.html { render '/shared/created'}
        format.json { render action: 'show', status: :created, location: @song }
      else
        format.html { render action: 'new' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update

    artist_id = update_artist_exist_or_new(params[:artist_name])

    album_id = update_album_exist_or_new(params[:album_name], params[:genre], artist_id)

    respond_to do |format|

      @song.album_id = album_id
      a = @song.album
      a.artist_id = artist_id
      a.save

      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:song_title, :track, :duration, :path, :filename, :composer)
    end

    def song_error
      puts "In song_error method, @err_msg = #{@err_msg}"
    end

    def artist_exist_or_new(artist_name)
      if Artist.all.collect{|a| a.name}.include? artist_name 
        a = Artist.where(name: artist_name)
        artist_id = a[0].id
      else
        @artist=Artist.new(name: artist_name)
        if @artist.name.empty?
          @err_msg = "The Album data requires an Artist, an Album Title and a Genre."
          render action: :song_error and return
        elsif !@artist.save
          format.html { render action: 'new' }
          format.json { render json: @artist.errors, status: :unprocessable_entity }
        end
        artist_id = @artist.id
      end
    end

    def album_exist_or_new(album_name, genre, artist_id)
      if Album.all.collect{|a| a.album_title}.include? album_name 
        a = Album.where(album_title: album_name)
        album_id = a[0].id
      else
        @album=Album.new(album_title: album_name, genre: genre, artist_id: artist_id)
        if @album.album_title.empty?||@album.genre.empty?
          @err_msg = "The Album data requires an Artist, an Album Title and a Genre."
          render action: :song_error and return
        elsif !@album.save
          format.html { render action: 'new' }
          format.json { render json: @album.errors, status: :unprocessable_entity }
        end
        album_id = @album.id
      end
    end      

    def update_artist_exist_or_new(artist_name)
      if Artist.all.collect{|a| a.name}.include? artist_name 
        a = Artist.where(name: artist_name)
        artist_id = a[0].id
      else
        @artist=Artist.new(name: artist_name)
        if @artist.name.empty?
          @err_msg = "The Album data requires an Artist, an Album Title and a Genre."
          render action: :song_error and return
        elsif !@artist.save
          format.html { render action: 'new' }
          format.json { render json: @artist.errors, status: :unprocessable_entity }
        end
        artist_id = @artist.id
      end
    end

    def update_album_exist_or_new(album_name, genre, artist_id)
      if Album.all.collect{|a| a.album_title}.include? album_name 
        a = Album.where(album_title: album_name)
        album_id = a[0].id
      else
        @album=Album.new(album_title: album_name, genre: genre, artist_id: artist_id)
        if @album.album_title.empty?||@album.genre.empty?
          @err_msg = "The Album data requires an Artist, an Album Title and a Genre."
          render action: :song_error and return
        else
         @album.save
        end
        album_id = @album.id
      end
    end

end

app/helpers/songs_helper.rb
module SongsHelper

	require 'rubygems'
	#require '/home/lecter/.rvm/gems/ruby-2.0.0-p353@MusicProject/gems/lctr_mp3-0.0.4/lib/lctr_mp3.rb'
	require 'lctr_mp3'
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @song.album.nil? %>
    <% exist_artist_name = @song.album.artist.name %>
    <% exist_album_title = @song.album.album_title %>
    <% exist_album_genre = @song.album.genre %>
  <% else %>
    <% exist_artist_name = "" %>
    <% exist_album_title = "" %>
    <% exist_album_genre = "" %>
  <% end %>

  <div class="field">
    <%= f.label :song_title %>*<br>
    <%= f.text_field :song_title %>
  </div>
  <div class="field">
    Artist*<br>
    <%= text_field_tag 'artist_name',exist_artist_name %><br>
  </div>
  <div class="field">
    Album*<br>
    <%= text_field_tag 'album_name', exist_album_title %>
  </div>    
  <div class="field">
    <%= f.label :track %>*<br>
    <%= f.number_field :track %>
  </div>
  <div class="field">
    <%= f.label :duration %>*<br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    Genre*<br>
    <%= text_field_tag 'genre', exist_album_genre %>
  </div>  
  <div class="field">
    <%= f.label :path %>*<br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :filename %>*<br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :composer %><br>
    <%= f.text_field :composer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div>
  <h3>* - Fields marked with an asterix are required.</h3>
  </div>

<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Song Library</h1>

<table>
  <thead>
  <table border="1">
    <tr>
      <th>Song Title</th>
      <th>Album Title</th>
      <th>Artist</th>
      <th>Track</th>
      <th>Duration</th>
      <th>Genre</th>
      <th>Path</th>
      <th>Filename</th>
      <th>Composer</th>
      <th>Musicians</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.song_title %></td>
        <td><%= song.album.album_title %></td>
        <td><%= song.album.artist.name %></td>
        <td><%= song.track %></td>
        <td><%= song.durationmin %></td>
        <td><%= song.album.genre %></td>
        <td><%= song.path %></td>
        <td><%= song.filename %></td>
        <td><%= song.composer %></td>
        <td><center>
          <% song.musicians.map do |m| %>
            <%= "#{m.first_name} #{m.last_name} -  
              #{m.instruments.collect{|i| i.name}.join ', '}" %><br>
          <% end %>
        </center></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %><br>
Add Song from tag:
<%= form_tag(:action => 'tag_entry') do %>
  <%= text_field_tag "tag_file_name", 'path and filename', :style => "color:grey; font-style:italic" %>
  <%= submit_tag "Add Song!" %>
<% end %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Song title:</strong>
  <%= @song.song_title %>
</p>

<p>
  <strong>Track:</strong>
  <%= @song.track %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @song.duration %>
</p>

<p>
  <strong>Path:</strong>
  <%= @song.path %>
</p>

<p>
  <strong>Filename:</strong>
  <%= @song.filename %>
</p>

<p>
  <strong>Composer:</strong>
  <%= @song.composer %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>

app/views/songs/song_error.html.erb
<html>
<body>
  <%= puts "In Song Error View, #{@err_msg}" %>
  <h1> <%= @err_msg %> </h1>
  In song_error
  <%= link_to('return', '/songs/') %>
</body>
</html>

app/views/songs/tag_entry.html.erb
<h1> Welcome to the tag entry page!!</h1>

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_title %>*<br>
    <%= f.text_field :song_title, :value => @tag.song_title %>
  </div>
  <div class="field">
    Artist*<br>
    <%= text_field_tag 'artist_name', @tag.artist %><br>
  </div>
  <div class="field">
    Album*<br>
    <%= text_field_tag 'album_name', @tag.album_title %>
  </div>    
  <div class="field">
    <%= f.label :track %>*<br>
    <%= f.text_field :track, :value => @tag.track %>
  </div>
  <div class="field">
    <%= f.label :duration %>*<br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    Genre*<br>
    <%= text_field_tag 'genre' %>
  </div>  
  <div class="field">
    <%= f.label :path %>*<br>
    <%= f.text_field :path, :value =>@tag_file_name %>
  </div>
  <div class="field">
    <%= f.label :filename %>*<br>
    <%= f.text_field :filename, :value => @tag_file_name %>
  </div>
  <div class="field">
    <%= f.label :composer %><br>
    <%= f.text_field :composer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <div>
  <h3>* - Fields marked with an asterix are required.</h3>
  </div>

<% end %>