config/routes.rb
MusicProject::Application.routes.draw do
  devise_for :users
  resources :artists

  resources :albums

  resources :songs

  get '/hello', to:  'home#hello'
  root to:  'home#hello'

  get '/purchase', to:  'home#amazon'
  get '/created', to: 'home#created'
  post '/tag_entry', to: 'songs#tag_entry'
  get '/song_error', to: 'songs#song_error'

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :artist
	has_many :songs, :dependent => :destroy

  validates :album_title, presence: true
  validates :genre, presence: true

  scope :sorted, -> {joins(:artist).order('artists.name')}

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.sorted
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create

    artist_id = artist_exist_or_new(params[:artist_name])

    @album = Album.new(album_params)
    @album.artist_id = artist_id

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update

    artist_id = update_artist_exist_or_new(params[:artist_name])


    respond_to do |format|
      @album.artist_id = artist_id
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:album_title, :year, :genre, :protected, :artist_id)
    end

    def blank_artist
    end

    def artist_exist_or_new(artist_name)
      if Artist.all.collect{|a| a.name}.include? artist_name 
        a = Artist.where(name: artist_name)
        artist_id = a[0].id
      else
        @artist=Artist.new(name: artist_name)
        if @artist.name.empty?
          redirect_to action: :blank_artist and return
        elsif @artist.save!
          format.html { render action: 'new'}
          format.json { render json: @artist.errors, status: :unprocessable_entity }
        end
        artist_id = @artist.id
      end
    end

    def update_artist_exist_or_new(artist_name)
      if Artist.all.collect{|a| a.name}.include? artist_name
        a = Artist.where(name: artist_name)
        artist_id = a[0].id
      else
        # params[:artist_name] = "Fred"
        @artist=Artist.new(name: artist_name)
        if @artist.name.empty?
          redirect_to action: :blank_artist and return
        else 
          @artist.save!
        end
        artist_id = @artist.id
      end
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper

end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @album.artist.nil? ? exist_artist_name = "" : exist_artist_name = @album.artist.name %>

  <div class="field">
    <%= f.label :album_title %><br>
    <%= f.text_field :album_title %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
    <div class="field">
    Artist<br>
    <%= text_field_tag 'artist_name', exist_artist_name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :protected %><br>
    <%= f.check_box :protected %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/blank_artist.html.erb
<html>
<body>
  <h1> Artists Field cannot be blank. </h1>
  <%= link_to('return', '/albums/new') %>
</body>
</html>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <thead>
  <table border="1">
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Year</th>
      <th>Genre</th>
      <th>Protected?</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.album_title %></td>
        <td><%= album.artist.name %></td>
        <td><%= album.year %></td>
        <td><%= album.genre %></td>
        <td><%= album.protected %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>